=== api-evangelist/ballerina/json-schema/central-api-package-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/ballerina/refs/heads/main/json-schema/central-api-package-schema.json",
  "title": "Package",
  "description": "Package schema from Ballerina Central API",
  "type": "object",
  "properties": {
    "organization": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "pullCount": {
      "type": "integer"
    },
    "createdDate": {
      "type": "string",
      "format": "date-time"
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "license": {
      "type": "string"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repositoryURL": {
      "type": "string",
      "format": "uri"
    },
    "readme": {
      "type": "string"
    },
    "modules": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Module"
      }
    },
    "versions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== api-evangelist/ballerina/examples/central-api-package-example.json
{
  "organization": "sample-value",
  "name": "my-package",
  "version": "1.0.0",
  "description": "sample-value",
  "pullCount": 32,
  "createdDate": "sample-value",
  "keywords": [
    "sample-value"
  ],
  "license": "sample-value",
  "authors": [
    "sample-value"
  ],
  "repositoryURL": "https://central.ballerina.io/package",
  "readme": "sample-value",
  "modules": [
    "sample-value"
  ],
  "versions": [
    "1.0.0"
  ]
}
