=== api-evangelist/ballerina/json-schema/central-api-package-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/ballerina/refs/heads/main/json-schema/central-api-package-summary-schema.json",
  "title": "PackageSummary",
  "description": "PackageSummary schema from Ballerina Central API",
  "type": "object",
  "properties": {
    "organization": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "platform": {
      "type": "string"
    },
    "ballerinaVersion": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "pullCount": {
      "type": "integer"
    },
    "createdDate": {
      "type": "string",
      "format": "date-time"
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "license": {
      "type": "string"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== api-evangelist/ballerina/examples/central-api-package-summary-example.json
{
  "organization": "sample-value",
  "name": "my-package",
  "version": "1.0.0",
  "platform": "sample-value",
  "ballerinaVersion": "1.0.0",
  "description": "sample-value",
  "pullCount": 71,
  "createdDate": "sample-value",
  "keywords": [
    "sample-value"
  ],
  "license": "sample-value",
  "authors": [
    "sample-value"
  ]
}
